#!/bin/bash

set -e

HOME=`echo ~`

export WINEPREFIX=/root/.wine
export WINEDEBUG=-all
export DEBIAN_FRONTEND=noninteractive
export GRADLE_VERSION=4.9

pushd .

# Install wine and tools, and initialize wine
sudo dpkg --add-architecture i386 && \
	apt-get update && \
	apt-get install -y wine wine32 wine64 unzip wget curl nano libtinfo-dev libtinfo5 && \
	wine wineboot --init && \
	wineserver -w && \
	sleep 5

mkdir -p $HOME/.wine/drive_c/dev/ && \
	cd $HOME/.wine/drive_c/dev/ && \
	wget --quiet https://services.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip && \
	unzip -q gradle-$GRADLE_VERSION-bin.zip && \
	rm -f gradle-$GRADLE_VERSION-bin.zip && \
	mv gradle-$GRADLE_VERSION gradle

mkdir -p $HOME/.wine/drive_c/dev/ && \
	cd $HOME/.wine/drive_c/dev/ && \
	wget --quiet https://download.java.net/java/GA/jdk10/10.0.2/19aef61b38124481863b1413dce1855f/13/openjdk-10.0.2_windows-x64_bin.tar.gz && \
	tar -xzf openjdk-10.0.2_windows-x64_bin.tar.gz && \
	rm -f openjdk-10.0.2_windows-x64_bin.tar.gz && \
	mv jdk-10.0.2 java && \
	rm java/lib/src.zip

cd $HOME && \
	export WINE_PATH="C:\\windows\\system32;C:\\windows;C:\\windows\\system32\\wbem;C:\\dev\\gradle\\bin;C:\\dev\\java\\bin" && \
	wine reg add "HKEY_CURRENT_USER\\Environment" /v JAVA_HOME /t REG_SZ /d c:\\dev\\java && \
	wine reg add "HKEY_CURRENT_USER\\Environment" /v PATH /t REG_SZ /d $WINE_PATH && \
	wineserver -w && \
	sleep 5

cd /usr/local/bin && \
	echo "#!/bin/bash\nwine cmd /c gradle \$*" > gradle-win && \
	echo "#!/bin/bash\nwine cmd /c \$*" > winecmd && \
	chmod +x gradle-win winecmd

popd

winecmd gradlew.bat $*
