#!/bin/bash
HOME=`echo ~` docker run --rm -it \
	-v "$PWD:/work:delegated" \
	-v "$HOME/.gradle:/home/user/.gradle:delegated" \
	-v "$HOME/.m2:/home/user/.m2:delegated" \
	-v "gradlew_konan_linux:/home/user/.konan:delegated" \
	soywiz/kotlin-native-win:java8 \
	$*
