#!/bin/bash
set -e
./gradlew publish && \
    ./gradlew_win publishMingwX64PublicationToMavenRepository && \
    echo Done

#./gradlew_linux publishLinuxX64PublicationToMavenRepository # Kotlin 1.3.30 crosscompiles linux on mac
#./gradlew_win publishMingwX64PublicationToMavenRepository publishMingwX86PublicationToMavenRepository

